### ISSUE TITLE
多言語対応

### ISSUE THREAD

**Issue by yamasy1549** [vivliostyle/vivliostyle.org#10]
- [x] URLをどうするか？
  1. `/en` `/ja` `/`
  2. `/ja` `/`
  - このとき検索結果にはどう表示される？
- ~~ブラウザの言語設定を見てページを遷移する~~
- ~~localStorageで言語設定を管理する~~

**Comment by uetchy** [comment]
参考サイト

- https://developer.mozilla.org

**Comment by yamasy1549** [comment]
> ユーザーの言語を認識して自動的にリダイレクトすることは避けてください
https://support.google.com/webmasters/answer/182192?hl=ja&ref_topic=2370587

デフォルトで `/` (== `/en`)、手動で `/ja` に切り替えられる、という形が良さそう

**Comment by MurakamiShinyu** [comment]
> デフォルトで `/` (== `/en`)、手動で `/ja` や `/en` に切り替えられる、という形が良さそう

そうすると `/hoge/` と `/en/hoge/` が同一のページということになり、重複するのであまりよくないと思います。 `/en/hoge/` は `/hoge/` にリダイレクトするのであれば、それでもよいと思います。
