### ISSUE TITLE
vivliostyle.org の表記ルールについて（和欧間スペース）

### ISSUE THREAD

**Issue by ogwata** [vivliostyle/vivliostyle.org#13]
2/2 開発者会議において、vivliostyle.org リニューアルに際して、[gatsby-ja](https://github.com/gatsbyjs/gatsby-ja) を参考にするよう助言されました。

[gatsby-ja 翻訳スタイルガイド](https://github.com/gatsbyjs/gatsby-ja/blob/master/style-guide.md#%E5%8D%8A%E8%A7%92%E3%81%A8%E5%85%A8%E8%A7%92%E3%81%AE%E3%82%B9%E3%83%9A%E3%83%BC%E3%82%B9)に以下のような項目があります。

> 半角と全角のスペース
> 半角と全角が切り替わる箇所にスペースをいれてください。

この方法の是非については、古くから甲論乙駁が繰り返されてきました。私自身は和欧間スペースは処理系定義にまかせるべき、あるいは検索の際不便になりがちといった理由から、ずっと「入れない派」できました。

とはいえ、今ではあまり拘りはなく、どちらでも統一されていれば良いと思ってます。ただ、流れに任せてなんとなく「入れる派」に転向（？）するのは少し抵抗があります。

もしよければ、どなたか「入れる派」のメリットについて教えてもらえないでしょうか。

**Comment by MurakamiShinyu** [comment]
CSS で自動的に和欧文間スペースを入れる機能が標準化・実装されるのはまだまだ先のことですので、それまでは Web に公開するようなテキストでは和欧文間に欧文のスペースを入れるという方法が使われるのは自然なことだろうと思います。欧文スペースの幅はフォントによりますが、1/4 em くらいが一般的です。これは JIS X 4051 や JLREQ で規定されている和欧文間スペースの幅と一致します。したがって、欧文のスペースを入れれば、結果的に CSS で和欧文間スペースを入れる機能が実現したのと同様の見た目になります。

また、欧文では単語どうしをスペースで区切るものであるので、欧文と隣接する別の言語の単語との間にもスペースを入れるのは当然という考え方もあります。

ブラウザで自動的に和欧文間スペースを入れる機能が使えるようになったら見直すとしても、それまでは、和欧文間に欧文のスペースを入れるという方法に統一でよいのでないでしょうか？

**Comment by ogwata** [comment]
>ブラウザで自動的に和欧文間スペースを入れる機能が使えるようになったら見直すとしても、それまでは、和欧文間に欧文のスペースを入れるという方法に統一でよいのでないでしょうか？

了解しました。そうしましょう。
このissueはクローズします。
